version: '3'

services:
  # MySQL
  db:
    container_name: mysql8
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: baloneolike@x
      TZ: Asia/Shanghai
    network_mode: "host"
    restart: always
    volumes:
      - '/home/mysqldb:/var/lib/mysql'